name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    branches:
      - main
      - 3.15-stable

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Determine what has changed
    outputs:
      filter: ${{ steps.filter.outputs.changes }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v3.0.0
      - name: Filter for repo changes
        uses: dorny/paths-filter@v2.10.2
        id: filter
        with:
          filters: |
            main:
              - 'main/*/APKBUILD'
            community: 
              - 'community/*/APKBUILD'
            testing:
              - 'testing/*/APKBUILD'
            
