name: CI
#https://github.com/addnab/docker-run-action
# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
      - main
      - '*-stable'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: abuild
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 20
      - name: abuild
        uses: addnab/docker-run-action@v3
        with:
          image: xoroxwb/abuild-ci:x86_64
          options: --privileged
          run: |
            build.sh

